"""initial schema

Revision ID: 5672fb838644
Revises: 
Create Date: 2026-10-01 01:29:12.478752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5672fb838644'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image_file', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_table('buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('damage', sa.String(length=30), nullable=True),
    sa.Column('guard', sa.String(length=30), nullable=True),
    sa.Column('startup', sa.Integer(), nullable=True),
    sa.Column('active', sa.String(length=30), nullable=True),
    sa.Column('recovery', sa.String(length=30), nullable=False),
    sa.Column('onblock', sa.String(length=30), nullable=True),
    sa.Column('attribute', sa.String(length=30), nullable=True),
    sa.Column('invuln', sa.String(length=50), nullable=True),
    sa.Column('image_file', sa.String(length=200), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buttons_character_id'), 'buttons', ['character_id'], unique=False)
    op.create_index(op.f('ix_buttons_id'), 'buttons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buttons_id'), table_name='buttons')
    op.drop_index(op.f('ix_buttons_character_id'), table_name='buttons')
    op.drop_table('buttons')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
